from typing import Any, Dict, List, Optional, Protocol


class StoreBackend(Protocol):
    def get_state(self) -> Dict[str, Any]: ...
    def replace_state(self, next_state: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_settings(self) -> Dict[str, Any]: ...
    def update_settings(self, partial_settings: Dict[str, Any]) -> Dict[str, Any]: ...
    def ensure_user(self, telegram_user: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_user(self, user_id: Any) -> Optional[Dict[str, Any]]: ...
    def list_users(self) -> List[Dict[str, Any]]: ...
    def update_user_fields(self, user_id: Any, fields: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def get_payments(self) -> List[Dict[str, Any]]: ...
    def record_payment_and_activate_subscription(
        self,
        user_id: Any,
        payment: Dict[str, Any],
        settings: Dict[str, Any],
        promo_code: Optional[str] = None,
    ) -> Dict[str, Any]: ...
    def grant_subscription_days(self, user_id: Any, days: int, reason: str = "admin_grant") -> Optional[Dict[str, Any]]: ...
